### ISSUE TITLE
total_steps

### ISSUE THREAD

**Issue by mklissa** [vuoristo/dqn-agent#1]
Hi, 
I was just wondering why you have two variables for total_steps: one in the DQNAgent and the other one in DQNModel, and both are initalized to 0 and seem to increase at different speeds. Wouldn't that lead to a target model update less frequent than if we had only one total_steps for the whole code?

Thank you

**Comment by vuoristo** [comment]
The target model is trained less frequently by design. So I believe the two counters are achieving the desired behaviour here. Using two counters and especially naming them both total_steps are admittedly confusing design decisions.
