### ISSUE TITLE
Instruction for resume-training?

### ISSUE THREAD

**Issue by isVoid** [vuoristo/dqn-agent#2]
So previously I have a model trained for 400K steps. And for some reason I have to interrupt the training. Now I would like to resume the previous training, what should I do?

Commands I have tried: python AtariAgent.py -l ./train/model.ckpt-990000.meta
which throws data loss error.

**Comment by vuoristo** [comment]
I'm not sure if I'm getting the same error, but loading the weights from file ./train/model.ckpt-990000 (dropping the .meta) helped for me.
